# Build stage
FROM node:22 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Nginx stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html/rsud-tangerang
COPY nginx.conf /etc/nginx/conf.d/default.conf   
EXPOSE 82
CMD ["nginx", "-g", "daemon off;"]
